<# LINE TO CREATE USER. YOU CAN REPLY THIS LINE AS MANY AS YOU NEED, TO EACH USER YOU WANT TO CREATE. #>
New-ADUser -Path 'OU=SECONDOU,OU=ROOTOU,DC=FQDNDCNAME,DC=FQDNPORTION' -Name "SHOWNAME" -SAMAccountName "NAME" -givenName FIRSTNAME -Surname SECONDNAME -UserPrincipalName EMAILACCOUNT@.COM
<# THIS LINE SET A DEFAULT PASSWORD TO ALL USERS OF YOUR DOMAIN CONTROLLER #>
DSQUERY user "OU=SECONDOU,OU=ROOTOU,DC=FQDNDCNAME,DC=FQDNPORTION" -limit 0 | DSMOD user -pwd "PASSWORD"